function results() {
    var firstname = document.getElementById('firstname').value;
    var lastname = document.getElementById('lastname').value;
    var title = document.getElementById('title').value;
    var email = document.getElementById('email').value;
    var ophone = document.getElementById('ophone').value;
    var mphone = document.getElementById('mphone').value;
    var department = document.getElementById('department').value;


    document.write("<p></p><h2>Please review your answers below</h2>");
    document.write("<h3> If all is correct: </br> - &nbsp; Highlight the signature block below. </br>- &nbsp; Right click and copy.  </br>This is what you will paste onto your Outlook signature.</h3><br/><br/> <hr><br/><br/> ");


    if (mphone.value === '') {
        document.getElementById('mobileDot').style.display = 'none';
    }


    if (department == 'BusinessDevelopment') {
        document.write("<div id='target' class='half' style='text-decoration: none;'> &nbsp;<div class = 'col-md-12 col-sm-12 col-xs-12'><div class = 'containerSign' style = 'font-family: helvetica; margin-left: 25px; text-align: left;'><div class='leftSign col-md-2 col-sm-2 col-xs-2' style = 'margin-top: 14px;font-family: helvetica; float: left;height: 210px;'><a style='text-decoration: none; color: #000;' href = 'http://www.askgpa.com/'><img src = 'https://s7.postimg.org/6gu7z2s97/GPAlogo_Email.png' width = '105' height = '115' alt = 'GPA Corporate Logo'></a></div><div class = 'rightSign col-md-4 col-sm-4 col-xs-4' style = 'margin-right: 10%; line-height: 1;'><div class='flName'style='padding-top: 1px;'><h4>" + firstname + " " + lastname + "</h4></div><div class='titleText' style='font-family: helvetica; margin-top: -88px;padding: 1px;'><h5>" + title + "</h5></div></br><div class = 'address' style='font-family: helvetica; font-size: 12px; margin-top: -38px; line-height:1.;'><a style='text-decoration: none; color: #000;' href = 'https://www.google.com/maps/place/GPA+Specialty+Substrate+Solutions/@41.8036997,-87.8372935,15z/data=!4m5!3m4!1s0x0:0xa090e9a0e74ba408!8m2!3d41.8036997!4d-87.8372935'>8701 W. 47th Street &nbsp<span class='dot' style='font-weight:900;'>.</span>&nbsp; McCook, IL 60525</a></br>Orders: &nbsp;<a style='text-decoration: none; color: #000;' href = 'tel://1-800-395-9000'>800-395-9000</a> <span class='dot' style='font-weight:900;'>.</span>&nbsp<a style='text-decoration: none; color: #000;' href = 'tel://1-" + mphone + "'>Mobile: &nbsp;" + mphone + "</a></br><span class='emailSection style='text-decoration: none; color: #000;'>" + email + "&nbsp;</span>");
        document.write("&nbsp;<span class='dot' style='font-weight:900;'>.</span>&nbsp&nbsp;Website:&nbsp;<a style='text-decoration: none; color: #000;' href = 'http://www.askgpa.com/'> askgpa.com </a></div><div class = 'SocialMediaIcons'style = 'margin-top: 5px; margin-left:2%;'><a  href = 'https://www.facebook.com/askgpa/'><img src ='https://s10.postimg.org/v1j9nsdeh/Facebook3.png' width='32' height='31' alt = 'Facebook'></a>&nbsp;&nbsp;<a href = 'https://www.twitter.com/askgpa'><img src = 'https://s10.postimg.org/5hgzhlzt5/twitter3.png' width='30' height='30'alt = 'Twitter'></a>&nbsp;&nbsp;<a href = 'https://www.linkedin.com/company/gpa-specialty-substrate-solutions'><img src = 'https://s10.postimg.org/83whylgqx/linked_In.png'width='30' height='30' alt = 'LinkedIn'></a>&nbsp;&nbsp;<a href = 'http://www.runiverse.org/main/authorization/signIntarget=http%3A%2F%2Fwww.runiverse.org%2F'><img src = 'https://s10.postimg.org/wgwbt15zt/RUniverse5.png' width='37' height='37' alt = 'RUniverse'></a></div></div></div></div></div>");
    } else if (department == 'CustomerService') {
        document.write("<div id='target' class='half' style='text-decoration: none;'> &nbsp;<div class = 'col-md-12 col-sm-2 col-xs-2'><div class = 'row'><div class = 'containerSign' style = 'font-family: helvetica; margin-left: 25px; text-align: left;'><div class='leftSign col-md-2 col-sm-4 col-xs-4' style = 'margin-top: 14px;font-family: helvetica; float: left;height: 210px;'><a style='text-decoration: none; color: #000;' href = 'http://www.askgpa.com/'><img src = 'https://s7.postimg.org/6gu7z2s97/GPAlogo_Email.png' width = '115' height = '125' alt = 'GPA Corporate Logo'></a></div><div class = 'row'><div class = 'rightSign' style = 'margin-right: 10%;'><div class='flName'style='padding-top: 1px;'><h4>" + firstname + " " + lastname + "</h4></div><div class='titleText' style='font-family: helvetica; margin-top: -48px;padding: 1px;'><h5>" + title + "</h5></div></br><div class = 'address' style='font-family: helvetica; font-size: 12px; margin-top: -38px; line-height:1.3;'><a style='text-decoration: none; color: #000;' href = 'https://www.google.com/maps/place/GPA+Specialty+Substrate+Solutions/@41.8036997,-87.8372935,15z/data=!4m5!3m4!1s0x0:0xa090e9a0e74ba408!8m2!3d41.8036997!4d-87.8372935'>8701 W. 47th Street &nbsp<span class='dot' style='font-weight:900;'>.</span>&nbsp; McCook, IL 60525</a></br>Orders: &nbsp;<a style='text-decoration: none; color: #000;' href = 'tel://1-800-395-9000'>800-395-9000</a>&nbsp;<span class='dot' style='font-weight:900;'>.</span>&nbsp;<a style='text-decoration: none; color: #000;' href = 'tel://1-561-8766'>Fax: &nbsp;800-395-3581</a>&nbsp;<a style='text-decoration: none; color: #0e3557;' href='tel://1-" + mphone + "'><span class='dot' style='font-weight:900;'>.</span>&nbsp;&nbsp;Mobile: &nbsp;" + mphone + "</a></br><span class='emailSection style='text-decoration: none; color: #000;'>" + email + "&nbsp;</span>");
        document.write("&nbsp;<span class='dot' style='font-weight:900;'>.</span>&nbsp;&nbsp;Website:&nbsp;<a style='text-decoration: none; color: #000;' href = 'http://www.askgpa.com/'> askgpa.com </a></div><div class = 'SocialMediaIcons'style = 'margin-top: 5px; margin-left:2%;'><a  href = 'https://www.facebook.com/askgpa/'><img src ='https://s10.postimg.org/v1j9nsdeh/Facebook3.png' width='32' height='31' alt = 'Facebook'></a>&nbsp;&nbsp;<a href = 'https://www.twitter.com/askgpa'><img src = 'https://s10.postimg.org/5hgzhlzt5/twitter3.png' width='30' height='30'alt = 'Twitter'></a>&nbsp;&nbsp;<a href = 'https://www.linkedin.com/company/gpa-specialty-substrate-solutions'><img src = 'https://s10.postimg.org/83whylgqx/linked_In.png'width='30' height='30' alt = 'LinkedIn'></a>&nbsp;&nbsp;<a href = 'http://www.runiverse.org/main/authorization/signIntarget=http%3A%2F%2Fwww.runiverse.org%2F'><img src = 'https://s10.postimg.org/wgwbt15zt/RUniverse5.png' width='37' height='37' alt = 'RUniverse'></a>&nbsp;<a href = 'https://www.youtube.com/user/askgpa'><img src = 'https://s10.postimg.org/3r9fw1mgp/youtube.png' width='29' height='29' alt = 'RUniverse'></a></div></div> </div> </div> </div> </div> </div>");
    } else if (department == 'Credit') {
        document.write("<div id='target' class='half' style='text-decoration: none;'> &nbsp;</div> <div class = 'col-md-12 col-sm-2 col-xs-2'><div class = 'row'><div class = 'containerSign' style = 'font-family: helvetica; margin-left: 25px; text-align: left;'><div class='leftSign col-md-2 col-sm-4 col-xs-4' style = 'font-family: helvetica; float: left;height: 210px;'><a style='text-decoration: none; color: #0e3557;' href = 'http://www.askgpa.com/'> <img src = 'https://s7.postimg.org/6gu7z2s97/GPAlogo_Email.png' width = '155' height = '175' alt = 'GPA Corporate Logo'> </a></div> <div class = 'row'><div class = 'rightSign' style = 'margin-right: 10%;'><div class='flName'style='padding-top: 4px;'><h2>" + firstname + " " + lastname + "</h2></div><div class='titleText' style='font-family: helvetica; margin-top: -39px;padding: 1px;'><h3>" + title + "</h3></div></br><div class = 'address' style='font-family: helvetica; margin-top: -20px; line-height:1.3;'><a style='text-decoration: none; color: #0e3557;' href = 'https://www.google.com/maps/place/GPA+Specialty+Substrate+Solutions/@41.8036997,-87.8372935,15z/data=!4m5!3m4!1s0x0:0xa090e9a0e74ba408!8m2!3d41.8036997!4d-87.8372935'>8701 W. 47th Street &nbsp<span class='dot' style='font-weight:900;'>.&nbsp</span>&nbspMcCook, IL 60525</a></div><a style='text-decoration: none; color: #0e3557;'href = 'tel://1-800-395-9000'>800-395-9000</a> Office &nbsp<span class='dot' style='font-weight:900; margin-bottom: -45%;'>.&nbsp</span>&nbsp<a style='text-decoration: none; color: #0e3557;' href = 'tel://1-800-395-3581'></a>800-395-3581 Fax");
        document.write("</br>email: &nbsp; " + email);
        document.write("<div class = 'siteAddress'style = 'margin-top: 28px;'><a style='text-decoration: none; color: #0e3557;' href = 'http://www.askgpa.com/'> askgpa.com </a><span class = 'SocialMediaIcons'style = 'margin-top: 55px; margin-left:15%; margin-right: -23px;'><a href = 'https://www.facebook.com/askgpa/'><img src ='https://s10.postimg.org/v1j9nsdeh/Facebook3.png'  alt = 'Facebook'></a> <a href = 'https://www.twitter.com/askgpa'><img src = 'https://s10.postimg.org/5hgzhlzt5/twitter3.png' alt = 'Twitter'></a><a href = 'https://www.linkedin.com/company/gpa-specialty-substrate-solutions'><img src = 'https://s10.postimg.org/83whylgqx/linked_In.png'width='32' height='32' alt = 'LinkedIn'></a><a href = 'http://www.runiverse.org/main/authorization/signIntarget=http%3A%2F%2Fwww.runiverse.org%2F'><img src = 'https://s10.postimg.org/wgwbt15zt/RUniverse5.png' width='40' height='40' alt = 'RUniverse'></a></span></div></div> </div> </div> </div> </div> </div>");
    } else if (department == 'PurchasingMerchandizing') {
        document.write("<div id='target' class='half' style='text-decoration: none;'> &nbsp;</div> <div class='col-md-12 col-sm-2 col-xs-2'><div class='row'><div class='containerSign' style='font-family: helvetica; margin-left: 25px; text-align: left;'><div class='leftSign col-md-2 col-sm-4 col-xs-4' style='font-family: helvetica; float: left;height: 210px;'><a style='text-decoration: none; color: #0e3557;' href='http://www.askgpa.com/'> <img src='https://s7.postimg.org/6gu7z2s97/GPAlogo_Email.png' width='155' height='175' alt='GPA Corporate Logo'> </a></div> <div class='row'><div class='rightSign' style='margin-right: 10%;'><div class='flName' style='padding-top: 4px;'><h2>" + firstname + " " + lastname + "</h2></div><div class='titleText' style='font-family: helvetica; margin-top: -39px;padding: 1px;'><h3>" + title + "</h3></div></br><div class='address' style='font-family: helvetica; margin-top: -20px; line-height:1.3;'><a style='text-decoration: none; color: #0e3557;' href='https://www.google.com/maps/place/GPA+Specialty+Substrate+Solutions/@41.8036997,-87.8372935,15z/data=!4m5!3m4!1s0x0:0xa090e9a0e74ba408!8m2!3d41.8036997!4d-87.8372935'>8701 W. 47th Street &nbsp<span class='dot' style='font-weight:900;'>.&nbsp</span>&nbspMcCook, IL 60525</a></div><a style='text-decoration: none; color: #0e3557;' href='tel://1-800-395-9000'>800-395-9000</a> Office &nbsp<span class='dot' style='font-weight:900;'>.&nbsp</span>&nbsp<a style='text-decoration: none; color: #0e3557;' href='tel://1-" + mphone + "'>" + mphone + "</a> Mobile");
        document.write("</br>email: &nbsp; " + email);
        document.write("<div class='siteAddress' style='margin-top: 28px;'><a style='text-decoration: none; color: #0e3557;' href='http://www.askgpa.com/'> askgpa.com </a><span class='SocialMediaIcons' style='margin-top: 55px; margin-left:15%; margin-right: -23px;'><a href='https://www.facebook.com/askgpa/'><img src='https://s10.postimg.org/v1j9nsdeh/Facebook3.png' alt='Facebook'></a> <a href='https://www.twitter.com/askgpa'><img src='https://s10.postimg.org/5hgzhlzt5/twitter3.png' alt='Twitter'></a><a href='https://www.linkedin.com/company/gpa-specialty-substrate-solutions'><img src='https://s10.postimg.org/83whylgqx/linked_In.png' width='32' height='32' alt='LinkedIn'></a><a href='http://www.runiverse.org/main/authorization/signIntarget=http%3A%2F%2Fwww.runiverse.org%2F'><img src='https://s10.postimg.org/wgwbt15zt/RUniverse5.png' width='40' height='40' alt='RUniverse'></a></a></span></div></div> </div> </div> </div> </div> </div>");
    } else {
        (department == 'Marketing')
        document.write("<div id='target' class='half' style='text-decoration: none;'> &nbsp;</div> <div class = 'col-md-2 col-sm-2 col-xs-2'><div class = 'row'><div class = 'containerSign' style = 'font-family: helvetica; margin-left: 25px; text-align: left;'><div class='leftSign col-md-2 col-sm-4 col-xs-4' style = 'font-family: helvetica; float: left;height: 210px;'><a style='text-decoration: none; color: #0e3557;' href = 'http://www.askgpa.com/'> <img src = 'https://s7.postimg.org/6gu7z2s97/GPAlogo_Email.png' width = '155' height = '175' alt = 'GPA Corporate Logo'> </a></div> <div class = 'row'><div class = 'rightSign' style = 'margin-right: 10%;'><div class='flName'style='padding-top: 4px;'><h2>" + firstname + " " + lastname + "</h2></div><div class='titleText' style='font-family: helvetica; margin-top: -39px;padding: 1px;'><h3>" + title + "</h3></div></br><div class = 'address' style='font-family: helvetica; margin-top: -20px; line-height:1.3;'><a style='text-decoration: none; color: #0e3557;' href = 'https://www.google.com/maps/place/GPA+Specialty+Substrate+Solutions/@41.8036997,-87.8372935,15z/data=!4m5!3m4!1s0x0:0xa090e9a0e74ba408!8m2!3d41.8036997!4d-87.8372935'>8701 W. 47th Street &nbsp<span class='dot' style='font-weight:900;'>.&nbsp</span>&nbspMcCook, IL 60525</a></div><a style='text-decoration: none; color: #0e3557;'href = 'tel://1-" + ophone + "'>" + ophone + "</a> Office");
        document.write("</br>email: &nbsp; " + email);
        document.write("<div class = 'siteAddress'style = 'margin-top: 28px;'><a style='text-decoration: none; color: #0e3557;' href = 'http://www.askgpa.com/'> askgpa.com </a><span class = 'SocialMediaIcons'style = 'margin-top: 55px; margin-left:15%; margin-right: -23px;'><a href = 'https://www.facebook.com/askgpa/'><img src ='https://s10.postimg.org/v1j9nsdeh/Facebook3.png'  alt = 'Facebook'></a> <a href = 'https://www.twitter.com/askgpa'><img src = 'https://s10.postimg.org/5hgzhlzt5/twitter3.png' alt = 'Twitter'></a><a href = 'https://www.linkedin.com/company/gpa-specialty-substrate-solutions'><img src = 'https://s10.postimg.org/83whylgqx/linked_In.png'width='32' height='32' alt = 'LinkedIn'></a><a href = 'http://www.runiverse.org/main/authorization/signIntarget=http%3A%2F%2Fwww.runiverse.org%2F'><img src = 'https://s10.postimg.org/wgwbt15zt/RUniverse5.png' width='40' height='40' alt = 'RUniverse'></a></a></span></div></div> </div> </div> </div> </div> </div>");
    }
}



$(window).resize(function () {
    //Resize
    var w = $(window).width();
    if (w < 768) {
        $('#target').css({
            'width': '100%'
        });
    } else {
        $('#target').css({
            'width': '500px'
        });
    }

});



